### ISSUE TITLE
Skip background class in calibration metrics 

### ISSUE THREAD

**Issue by benolmbrt** [Bala93/MarginLoss#11]
Hi and thanks for sharing your code,

In your paper about the Margin-loss, you wrote that "both ECE and CECE are obtained by considering only the foreground regions. The reason behind this is that most of the correct –and certain– predictions are from the background. "

However when looking at the metrics implementation I can't determine where you remove the background class in the computation. Could you provide insights about this ?

Best 
Benjamin

**Comment by Bala93** [comment]
https://github.com/Bala93/MarginLoss/blob/master/calibrate/evaluation/segment_calibrate_evaluator.py#L77-L79 -- Please find it here. We are considering the label map which are not equal to 0 (background).
